<?php

/**
 * PlugintmcCatalogueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugintmcCatalogueTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlugintmcCatalogueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlugintmcCatalogue');
    }
}